### ISSUE TITLE
Issue in running AI_platform_demo.ipynb

### ISSUE THREAD

**Issue by hongirsa** [hongirsa/ALR#5]
I have issue in running the sample code (https://github.com/hongirsa/ALR/blob/main/development/AI_platform_demo.ipynb) provided by Google. 

**Quite a few tests for running this sample code by Google, always stuck in the step -set Cloud project and then run the eeifier**

!earthengine set_project {PROJECT}
!earthengine model prepare --source_dir {config.MODEL_DIR} --dest_dir {config.EEIFIED_DIR} --input {input_dict} --output {output_dict}

**RESOURCE_EXHAUSTED: SameWorkerRecvDone unable to allocate output tensor**

The testing can be found at https://github.com/hongirsa/ALR/blob/main/testing%20AI_platform_demo/AI_DEMO_TESTING.pdf

**Comment by rfernand387** [comment]
Giovanni indicated this is due to 8Gb ram limit of P4 GPU that was being used.   He confirmed it works with V100s.  Gang will verify if this limit impacts our smaller models or if in any case AI platform training avoids issue,

Would be nice to GEE on line docs to use simpler examples.
